// --------------------------------------------------------
// Auto-generated by SoundNamesGenerator
// DO NOT EDIT MANUALLY!
// --------------------------------------------------------

public static class SoundNames
{
    public const string MoveDice = "MoveDice";
    public const string ButtonPressed = "ButtonPressed";
    public const string DiceRoll = "DiceRoll";
    public const string MoveHand = "MoveHand";
    public const string Error = "Error";
    public const string Lyghting = "Lyghting";
    public const string UIWoosh = "UIWoosh";

}